inherit_from: .rubocop_todo.yml

Layout/ParameterAlignment:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes
